### ISSUE TITLE
Changing the Font Family

### ISSUE THREAD

**Issue by suraj-9849** [apu52/METAVERSE#639] opened 2024-05-16 10:52 UTC
![image](https://github.com/apu52/METAVERSE/assets/146669517/b9f4a111-0593-4797-9890-9e40bdf4bcc7)

The font which was used here doesnot match the UI of the website so can you please assign this to me under @gssoc @apu52

**Comment by apu52** [comment] 2024-05-17 15:32
@suraj-9849 The issue is not clear . Can you please raise your issue with the issue templates so that it will be more understanding .

![image](https://github.com/apu52/METAVERSE/assets/114172928/e4d78ea4-57d4-4ded-9366-9de3d35a0718)

Use this templates.

Sorry to close this issue for now.

**Closed by apu52** 2024-05-17 15:32 UTC
Labels: bug, enhancement, good first issue
